# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: 'backend'
        ref: ${{ github.ref }} 
        token: ${{ secrets.GITHUB_TOKEN }} 

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: ./backend

    - name: Create .env file
      run: |
        touch .env
        echo "${{ secrets.REACT_ENV_FILE }}" > .env
      working-directory: ./backend

