name: React CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: 'React-CRUD/React-CRUD/backend' # Adjust path to target the correct directory
        ref: ${{ github.ref }} 
        token: ${{ secrets.GITHUB_TOKEN }} 

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
      working-directory: ./React-CRUD/React-CRUD/backend # Set working directory to backend

    - name: Install dependencies
      run: npm ci
      working-directory: ./React-CRUD/React-CRUD/backend # Set working directory to backend

    - name: Create .env file
      run: |
        touch .env
        echo "${{ secrets.REACT_ENV_FILE }}" > .env
      working-directory: ./React-CRUD/React-CRUD/backend # Set working directory to backend
